[general]
live_config_reload = true

[colors.bright]
black = "#202020"
blue = "#a5d6ff"
cyan = "#88afa2"
green = "#90a959"
magenta = "#aa759f"
red = "#cc6666"
white = "#e1e1e1"
yellow = "#f4bf75"

[colors.cursor]
cursor = "#d0d0d0"
text = "#151515"

[colors.dim]
black = "#373737"
blue = "#7e97ab"
cyan = "#88afa2"
green = "#90a959"
magenta = "#aa759f"
red = "#cc6666"
white = "#e1e1e1"
yellow = "#f4bf75"

[colors.normal]
black = "#171717"
blue = "#a5d6ff"
cyan = "#88afa2"
green = "#90a959"
magenta = "#aa759f"
red = "#cc6666"
white = "#e1e1e1"
yellow = "#f4bf75"

[colors.primary]
background = "#151515"
foreground = "#e1e1e1"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Medium"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Medium Italic"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Light"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
title = "Terminal"

[window.padding]
x = 5
y = 0
